/* eslint-disable prettier/prettier */
export const BASE_URL_SHIPOP = 'http://whola.vtexcommercestable.com.br/'
export const BASE_URL_PRICE ='https://api.vtex.com/whola/'
export const VTEX_API_KEY = 'vtexappkey-whola-YQKUWG'
export const VTEX_API_TOKEN ='ZJBTCSQUWNQLGWAWKUOXTZJFFVDLZPNWQUDVWFHWAAENEDGDYYPNOGMYWXUXKZVUDMCFTVLSUBKHHKHORBXFMBMRMAYYADFJZPHUICWXLDXBPOGCGZJQUWLTBKNIBBPM'
export const HUBSPOT_TOKEN = 'pat-ap1-f78dcafd-5027-4d25-bef5-86004bae24fa'
export const HUBSPOT_GET_CONTACT_URL ='https://api.hubapi.com/contacts/v1/contact/email/'
export const HUBSPOT_UPDATE_CONTACT_URL='https://api.hubapi.com/crm/v3/objects/contacts/'
export const HUBSPOT_CREATE_CONTACT_URL='https://api.hubapi.com/crm/v3/objects/contacts'
export const HUBSPOT_GET_DEAL_BY_NAME='https://api.hubapi.com/crm/v3/objects/deals/search'
export const HUBSPOT_UPDATE_DEAL_URL='https://api.hubapi.com/crm/v3/objects/deals/'
export const HUBSPOT_CREATE_DEAL_URL='https://api.hubapi.com/crm/v3/objects/deals'
export const HUBSPOT_SEARCH_PRODUCT_URL='https://api.hubapi.com/crm/v3/objects/products/search'
export const HUBSPOT_SEARCH_ITEM_LINE_URL='https://api.hubapi.com/crm/v3/objects/line_items'
export const HUBSPOT_CREATE_ITEM_LINE_URL='https://api.hubapi.com/crm/v3/objects/line_items'
export const HUBSPOT_CREATE_PRODUCT_URL='https://api.hubapi.com/crm/v3/objects/products'
export const HUBSPOT_SEARCH_COMPANY_BY_NAME_URL='https://api.hubapi.com/crm/v3/objects/companies/search'
export const HUBSPOT_CREATE_COMPANY_URL='https://api.hubapi.com/crm/v3/objects/companies'
